version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: python:3.10-slim
    command: python main.py
    volumes:
      - ./app:/app
    profiles:
      - cpu

  app-gpu:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime
    command: python main.py
    volumes:
      - ./app:/app
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    profiles:
      - gpu
